### ISSUE TITLE
Not usage in `auth.headers` object

### ISSUE THREAD

**Issue by MatanYadaev** [larasocket/larasocket-js#2]
https://github.com/larasocket/larasocket-js/blob/23c8f424b980810723263656b71d5bf21eff09a0/src/util/larasocket-websocket.ts#L157

I've added the `auth.headers` object to the options parameter, but `larasocket-js` didn't add it to the auth request. There's no option to authenticate using JWT.

**Comment by larasocket** [comment]
What is your use case for needing to do this?

Larasocket-js should handle all the authentication for you.

**Comment by MatanYadaev** [comment]
@larasocket I don't remember. It was long ago.
