### ISSUE TITLE
Browser console error

### ISSUE THREAD

**Issue by mikemand** [larasocket/larasocket-js#3]
I just deployed to production after testing on my staging server for a few weeks to see if this will work to replace Pusher. Looks promising so far, but I have an error in production that did not exist in staging.

Here is the error from my browser's console:

```
Uncaught (in promise) SyntaxError: Unexpected end of JSON input

Promise.then (async)
```
|    |    |    |
| -- | -- | -- |
| e.subscribe | @ | larasocket-manager.js:48|
| c.subscribe | @ | larasocket-channel.js:44|
| c | @ | larasocket-channel.js:37|
| c | @ | larasocket-private-channel.js:25|
| c.privateChannel | @ | larasocket-connector.js:59|
| value | @ | echo.js:1422|

I can share a sanitized version of my implementation if you need it.

**Comment by larasocket** [comment]
Sorry for the delays! Are you still running into issues?
